name: Check Appointment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "*/15 7-17 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - run: npm ci
    - run: ./node_modules/.bin/cypress run

    - name: Upload Artifact When appointment is available
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: appointment-available.mp4
        path: cypress/videos/termin_check_spec.js.mp4
        retention-days: 2

    - name: Upload Artifact When appointment is not available
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: appointment-unavailable.mp4
        path: cypress/videos/termin_check_spec.js.mp4
        retention-days: 1
