name: Check Appointment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "*/10 7-17 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - run: npm ci
    - run: ./node_modules/.bin/cypress run

    - name: Upload Artifact When appointment is available
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: appointment-available.mp4
        path: cypress/videos/termin_check_spec.js.mp4
        retention-days: 2

    - name: Send mail On Appointment Available
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: Appointment is available
        # Required recipients' addresses:
        to: ${{ secrets.EMAIL_TO }}
        # Required sender full name (address can be skipped):
        from: Munich Driver Licence Page Checker
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: Appoint Should be available
        # Optional carbon copy recipients:
        cc: ${{secrets.MAIL_USERNAME}}
        # Optional recipient of the email response:
        reply_to: ${{secrets.MAIL_USERNAME}}
        # Optional Message ID this message is replying to:
        in_reply_to: ${{secrets.MAIL_USERNAME}}
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:
        attachments: cypress/videos/termin_check_spec.js.mp4
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: high

    - name: Upload Artifact When appointment is not available
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: appointment-unavailable.mp4
        path: cypress/videos/termin_check_spec.js.mp4
        retention-days: 1
