name: Check Appointment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - run: npm ci
    - run: ./node_modules/.bin/cypress run
